name: Run Tests on Pull Request

# Run action on Pull Requests to master
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # We'll want to run the commands local to either the dotnet or React directories
    env:
      react-app-dir: ./tenant-file/portal-app
      dotnet-app-dir: ./TenantFile

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Set up dotnet
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    # Execute the dotnet tests
    - run: dotnet test
      working-directory: ${{env.dotnet-app-dir}}
    
    # Install the npm dependencies
    - name: Install Dependencies
      run: npm ci
      working-directory: ${{env.react-app-dir}}
    
    # Run the linter
    - name: Run ESLint
      run: npm run lint
      working-directory: ${{env.react-app-dir}}

    # Build the React app
    - name: Build the React App
      run: npm run build
      working-directory: ${{env.react-app-dir}}
    
    # Execute the React tests
#     - name: Test the React App
#       run: npm run test
#       working-directory: ${{env.react-app-dir}}
